// Generated by CodiumAI

import { render, screen } from "@testing-library/react";
import Button from "./Button";

describe("Button", () => {
  // Renders a button element with the provided children
  it("should render a button element with the provided children", () => {
    render(<Button>Test Button</Button>);
    const buttonElement = screen.getByText("Test Button");
    expect(buttonElement).toBeInTheDocument();
    expect(buttonElement.tagName).toBe("BUTTON");
  });

  // Applies default primary color and medium size if no props are passed
  it("should apply default primary color and medium size if no props are passed", () => {
    render(<Button />);
    const buttonElement = screen.getByText("Click me");
    expect(buttonElement).toHaveClass("bg-primary-main");
    expect(buttonElement).toHaveClass("text-sm");
  });

  // Applies the provided color and size props
  it("should apply the provided color and size props", () => {
    render(<Button color="secondary" size="lg" />);
    const buttonElement = screen.getByText("Click me");
    expect(buttonElement).toHaveClass("bg-secondary-main");
    expect(buttonElement).toHaveClass("text-base");
  });
});
