// Generated by CodiumAI

import { render } from "@testing-library/react";
import LoadingFetch from "./LoadingFetch";

describe("LoadingFetch", () => {
  it("renders with the default size", () => {
    const { container } = render(<LoadingFetch />);
    const svgElement = container.querySelector("svg");

    // Add assertions based on your component's expected behavior
    expect(svgElement).toHaveClass("w-8 h-8");
  });

  it("renders with the specified size", () => {
    const { container } = render(<LoadingFetch size="sm" />);
    const svgElement = container.querySelector("svg");

    // Add assertions based on your component's expected behavior
    expect(svgElement).toHaveClass("w-6 h-6");
  });
});
